# Generated by Django 5.0.1 on 2024-01-17 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
